= Programmierung mit Python für Programmierer:: Kapitel 2 - Kontrollstrukturen
Dr. Christian Heckler
:icons: font
:sectids!:
:imagesdir: ../bilder
:title-separator: ::
include::../Build/attributes-de.adoc[]

== Vorbemerkungen

* Verwendete Literatur: siehe Referenzen
* Verwendete Symbole:
** icon:exclamation-circle[]: Beispielprogramm
** icon:info-circle[]: Weitere Erläuterungen im Kurs
** icon:question-circle[]: Übung


== Ein- und Ausgabe

* Eingabe:
** Input-Funktion: `eingabe = input("Ihre Eingabe")`
** Die Input-Funktion liefert immer eine Zeichenkette zurück.
** Möchte man also eine Zahl eingeben, muss die Zeichenkette konvertiert werden:
+
[source,python]
----
zahl = float(input("Eingabe Zahl: " ))
----
* Ausgabe:
** Print-Funktion
** Ausgabe mehrere Objekte durch Komma getrennt
** Automatische Umwandlung in Zeichenkette
** Bsp.: `print("Das Ergebnis ist:", 42)`


== Anweisungsblöcke

* Anweisungen werden in „Anweisungsblöcke“ strukturiert.
* Dies geschieht in Python durch Einrückung.
* Anweisung mit dergleichen Einrücktiefe gehören dabei zusammen und bilden einen Block 
* Die Einrückungen müssen einheitlich mit Leerzeichen oder Tabulatoren erfolgen.
* Empfehlung:
** Leerzeichen (Tabulatortaste mit Leerzeichen „belegen“)
** Pro Stufe 4 Leerzeichen


== Bedingte Anweisungen

Drei Formen:

* Einfache `if`-Anweisung: 
** Wenn eine Bedingung erfüllt ist, werden die folgenden Anweisungen (Anweisungsblock) ausgeführt.
** Andernfalls nicht, und die Programmausführung geht hinter der `if`-Anweisung weiter
* `if … else`: 
** Je nach Bedingung wir der eine oder der andere Anweisungsblock ausgeführt
* `elif`: 
** Vereinfachte Schreibweise bei verschachtelten Bedingungen


== Einfache if-Anweisungen

* Allgemeine Form
+
[source,python]
----
if bedingung:
    anweisungen
anweisungen
----

* Beispiel <<Kle>>:
+
[source,python]
----
alter = int(input("Dein Alter"))
if alter < 12:
    print("Zu jung")
    print("Waehle einen anderen Film")
print("Programmende") 
----

== If-Anweisung mit Else-Teil

* Allgemeine Form
+
[source,python]
----
if bedingung:
    anweisungen
else:
    anweisungen
anweisungen
----

* Beispiel <<Kle>>:
+
[source,python]
----
alter = int(input("Dein Alter"))
if alter < 12:
    print("Zu jung")
    print("Waehle einen anderen Film")
else:
    print("Viel Spass")
print("Programmende") 
----
	
== „Verschachtelte“ Blöcke	
	
* In einem Anwendungsblock, der in einer If-Anweisung vorkommt, kann auch eine weitere If-Anweisung vorkommen.
* Das nennt man dann verschachtelte If-Anweisung.	
* Bsp <<Kle>>:
	
[source,python]
----
alter = int(input("Dein Alter"))
if alter < 4:
    print("Der Film ist zu kompliziert")
else:
    if alter < 12:
        print("Viel Spass")
    else:
        if alter < 16:
            print("Bist Du Dir sicher?")
        else:
            print("Wollen Sie sich das antun?")
print("Programmende") 
----

== Elif

* Das ist im Zweifelsfall schwer zu lesen. Daher gibt es mit „elif“ eine Abkürzung <<Kle>>

[source,python]
----
alter = int(input("Dein Alter"))
if alter < 4:
    print("Der Film ist zu kompliziert")
elif alter < 12:
    print("Viel Spass")
elif alter < 16:
    print("Bist Du Dir sicher?")
else:
    print("Wollen Sie sich das antun?")
print("Programmende") 
----


== Kurzschreibweisen

* Den „ternärem Operator“ (`x = bedingung ? wert1 : wert2`) gibt es nicht. Stattdessen:
+
[source,python]
----
x = wert1 if bedingung else wert2
----
* Einzeilige Bedingungen:
+
[source,python]
----
if bedingung: anweisung
----
* Kein Switch. Statt dessen:
** `elif` (insbesondere einzeilig, s. oben)
** evtl. Verwendung von Dictionaries


== Bedingungen

* Was genau steht hinter dem „if“?
* Ein „Ausdruck“, dessen Wert „wahr“ oder „falsch“ ist.
* Vergleichsoperatoren icon:info-circle[]:
+
|===
|Operator | Bedeutung | Beispiel

|`==` |gleich         |`42 == 42`
|`!=` |ungleich       |`42 != 43`
|`<`  |kleiner        |`42 < 43`
|`\<=`|kleiner gleich |`42 \<= 42`
|`>`  |größer         |`43 > 42`
|`>=` |größer gleich  |`42 >= 42`
|===
	
	
== Bedingungen II

* Der Ausdruck hinter `if` wird automatisch nach bool konvertiert, z.B.
+
[source,python]
----
liste = []
if liste: <1>
----
<1> Statt: `if len(liste) == 0:`
* Zu `False` ausgewertet wird:
** numerische Null-Werte
** leere Zeichenketten
** leere Listen, leere Tupel, leere Dictionaries
** Der `None`-Wert


== Schleifen

* In Python gibt es zwei Typen von Schleifen:
** `while`-Schleife
** `for`-Schleife

== Die While-Schleife

* Allgemeine Form:
+
----
while Bedingung:
    code_block
weitere Anweisungen
----
* Solange die Bedingung (_Schleifenkopf_, _Header_) erfüllt ist, wir der Code-Block (_Schleifenrumpf_) ausgeführt.
* Danach wird mit den „weiteren Anweisungen“ fortgefahren
* Ist die Bedingung „von Anfang an“ nicht erfüllt, wird der Schleifenrumpf überhaupt nicht durchlaufen.
* Natürlich kann der Code-Block wieder Schleifen enthalten (man spricht dann von _verschachtelten Schleifen_.)



== Break und Continue

* `break`: 
** Die Ausführung des Schleifenrumpfes wird abgebrochen. 
** Es wird mit der ersten Anweisung hinter der Schleife fortgefahren.
** Beispiel: `while.py` icon:exclamation-circle[]
* `continue`: 
** Die Ausführung des Schleifenrumpfes wird abgebrochen. 
** Es wird mit dem Schleifenkopf (Bedingung) fortgefahren.
** Beispiel: continue.py icon:exclamation-circle[]
* Beide Anweisungen wirken auf die aktuelle Schleife. Nicht auf evtl. vorhandene äußere Schleifen.


== Else-Teil einer While-Schleife

* Python-Spezialität.
* Der `else`-Teil wird ausgeführt, wenn und sobald die Schleifenbedingung nicht mehr zu trifft.
* Beim Verlassen der Schleife via `break` wird der `else`-Teil nicht ausgeführt.
* Beispiel: Zahlenraten icon:exclamation-circle[]
* Übung: Wie würde man das implementieren, wenn es kein Else der While-Schleife gäbe? icon:question-circle[]


== Die For-Schleife

* Allgemeine Form:
+
----
for variable in kollektion:
    code_block
weitere Anweisungen
----
* `variable`: Eine beliebige (auch neue) Variable.
* `kollektion`: Ein Ausdruck, der ein iterierbares Objekt bezeichnet (s. später)
* Der `code_block` wird so oft durchlaufen, wie es Elemente in der Kollektion gibt.
* In jedem Schleifendurchlauf nimmt die `variable` einen Wert der Kollektion an.
* Wenn alle Element durchlaufen wurden, wird das Programm mit den `weitere Anweisungen` fortgesetzt.


== For-Schleife: Beispiel

[source,python]
----
for buchstabe in "Python":
    print("Aktueller Buchstabe: ", buchstabe)
----

* Als Schleifenvariable (hier `buchstabe`) kann eine beliebige Variable verwendet werden (neu oder vorher schon verwendet).
* Im Beispiel wird der Schleifenrumpf 6 mal durchlaufen.
* Im ersten Schleifendurchlauf enthält die Variable `buchstabe` den Wert `"P"`.
* Im zweiten Schleifendurchlauf enthält die Variable `buchstabe` den Wert `"y"`.
* usw. 


== For-Schleife: Sonstiges

* Iteration über beliebige „iterierbare Objekte“
** Listen, Tupel
** Strings
** Dictionaries
** auch eigene Klassen, wenn sie die entspr. Methoden impl.

* Auch bei for-Schleifen:
** break
** continue
** else-Teil

* Weiteres Beispiel: `for.py` icon:exclamation-circle[]


== „Klassische“ For-Schleifen

* In anderen Programmiersprachen gibt es häufig For-Schleifen, die einen Bereich von ganzen Zahlen durchlaufen, z.B. Java, C(++):
+
----
for (int i=1; i<13; i++) {}
----
* Diese werden häufig benötigt, um die Indizes einer Zeichenkette oder einer Liste zu durchlaufen.
* Da man in Python mit der For-Schleife direkt über solche Objekte schleifen kann, wird die klassische Form selten benötigt.


== Range-Funktion

* Wenn doch, gibt es in Python die `range`-Funktion:
** liefert einen Bereich ganzer Zahlen, über den man iterieren kann.
** Bsp.:
+
[source,python]
----
for i in range(1,13):
    print("Monat: ", i)
----
** Es wird nicht a priori eine Liste der Zahlen erstellt.


== Schleife über Listen

* Ändert man eine Liste während man über die Liste schleift, sollte man über eine Kopie der Liste schleifen.
* Andernfalls könnte es zu Verwerfungen kommen.
* Bsp.: schleife_liste_kopie.py icon:exclamation-circle[]

== Referenzen

[bibliography]
* [[[Ste]]] Ralph Steyer: Programmierung Grundlagen, Herdt-Verlag
* [[[Kle]]] Bernd Klein: Einführung in Python 3, Hanser-Verlag
* [[[Kof]]] Kofler: Python – Der Grundkurs, Rheinwerk Computing
* [[[EK]]] Johannes Ernesti, Peter Kaiser: Python 3 – Das umfassende Handbuch, Rheinwerk Computing
* [[[Mat]]] Eric Matthes: Python Crashkurs – Eine praktische, projektbasierte Programmiereinführung, dpunkt.verlag
* [[[Swe]]] Sweigart: Eigene Spiele programmieren: Python lernen

